### ISSUE TITLE
`image_reader` problem with ".jpeg" files

### ISSUE THREAD

**Issue by njlyon0** [J0vid/Colormesh#13]
I'm working with a student to use the `tps.warp` function and realized that `image_reader` throws an error if the file ends in ".jpeg" rather than ".jpg"

If all of the files in the folder passed to the `imagedir` argument of `tps.warp` are ".jpeg" you get the following error:

```
Error in image_reader(imagedir, image.files[image.files.san.ext == image.names[i]]) : 
  Could not find  in the directory provided. Do the names provided match the images in the directory?
```

I believe it's because [line 14]( https://github.com/J0vid/Colormesh/blob/master/R/image_reader.R#L14) of `image_reader` manually specifies supported file extensions and only "jpg" (no "e") is supported. When the student changed her file names to remove the "e" in the extension the code worked as designed.

Also, I noticed that the lowercase "tif" is duplicated where I think one should be "tiff" (with two "f"s) which might cause a similar error for that file type.

Thanks for making such a useful package!

**Comment by J0vid** [comment]
Hi, apologies for the slow response. I'm happy to fix this in the code by myself, but if you are at all interested in becoming a contributor to the package, I encourage you to fork this repo, make the fixes you identified, and open a pull request. Once I merge that, you get credit as a contributor on the project on github. It's up to you if you want that credit, otherwise I'll just fix it directly. 

Let me know what you prefer, and thanks for using the package and figuring out the fix. 

-David

**Comment by njlyon0** [comment]
No apologies needed and thanks for the offer of contribution credit!

I opened a PR and while I was at it I updated the accepted image file type vector for all the functions where I saw it. Happy to undo that and restrict to just the `image_reader` and `tps.warp` functions if you'd prefer!

**Comment by J0vid** [comment]
Nice, it's now merged to main 😄
