### ISSUE TITLE
Error with 1 round of triangulation

### ISSUE THREAD

**Issue by jennv848** [J0vid/Colormesh#5]
When num.passes = 1 in the tri.surf function, an error is thrown when I try to use RGB measure. This only appears when linearize.color.space = T since there is some math being performed on the NA that appear in the perimeter. 
Here is an example of the behavior:
```R
specimen.factors <- read.csv(system.file("extdata", "specimen_factors.csv", package = "Colormesh"), header = F)
consensus <- tps2array(system.file("extdata", "consensus_LM_coords.TPS", package = "Colormesh"))
test.image <- image_reader(paste0(path.package("Colormesh"),"/extdata/unwarped_images/"), "GPLP_unw_001.jpg")
delaunay.map <- tri.surf(consensus, point.map = c(1,8:17,2, 18:19,3,20:27,4, 28:42,5,43:52,6,53:54,7,55:62), 1, test.image)

rgb.test <- rgb.measure(imagedir = paste0(path.package("Colormesh"),"/extdata/unwarped_images/"), image.names = specimen.factors[,2], delaunay.map = delaunay.map, linearize.color.space = T)
```

**Comment by J0vid** [comment]
I think I've fixed this in https://github.com/J0vid/Colormesh/commit/87b96adabbbb3e1a86227195d7c27b9f59a0b165. The example in the documentation for ?rgb.measure works if you change the number of Delaunay triangulations to 1 in tri.surf.

This bug came about because I thought I was clever and sampled perimeter points in the same loop as I sampled interior points. That doesn't work if there are more perimeter points than interior points, which is exactly what happens when there's only 1 round of triangulations. 

Check it out and let me know if the fix works for your data.
